# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: activity_service.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'activity_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x61\x63tivity_service.proto\"7\n\x0eWorkoutRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x14\n\x0cworkout_type\x18\x02 \x01(\t\"9\n\x0fWorkoutResponse\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x12\n\nstart_time\x18\x02 \x01(\t2\x83\x01\n\x0f\x41\x63tivityService\x12\x38\n\x13StartWorkoutSession\x12\x0f.WorkoutRequest\x1a\x10.WorkoutResponse\x12\x36\n\x11\x45ndWorkoutSession\x12\x0f.WorkoutRequest\x1a\x10.WorkoutResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'activity_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WORKOUTREQUEST']._serialized_start=26
  _globals['_WORKOUTREQUEST']._serialized_end=81
  _globals['_WORKOUTRESPONSE']._serialized_start=83
  _globals['_WORKOUTRESPONSE']._serialized_end=140
  _globals['_ACTIVITYSERVICE']._serialized_start=143
  _globals['_ACTIVITYSERVICE']._serialized_end=274
# @@protoc_insertion_point(module_scope)
